/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Danton
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelSet = new javax.swing.JLabel();
        btnAddPontoA = new javax.swing.JButton();
        btnRemovePontoA = new javax.swing.JButton();
        btnAddPontoB = new javax.swing.JButton();
        btnRemovePontoB = new javax.swing.JButton();
        labelPontosEquipeB = new javax.swing.JLabel();
        labelPontosEquipeA = new javax.swing.JLabel();
        labelEquipeA = new javax.swing.JLabel();
        labelEquipeB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSets = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("SET");

        labelSet.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelSet.setText("nSet");

        btnAddPontoA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnAddPontoA.setText("+");

        btnRemovePontoA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnRemovePontoA.setText("-");

        btnAddPontoB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnAddPontoB.setText("+");

        btnRemovePontoB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnRemovePontoB.setText("-");

        labelPontosEquipeB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelPontosEquipeB.setText("0");

        labelPontosEquipeA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelPontosEquipeA.setText("0");

        labelEquipeA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelEquipeA.setText("EquipeA");

        labelEquipeB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelEquipeB.setText("EquipeB");

        tableSets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableSets);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddPontoA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelPontosEquipeA, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemovePontoA, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddPontoB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPontosEquipeB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRemovePontoB, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEquipeA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelEquipeB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSet)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelSet))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEquipeA)
                    .addComponent(labelEquipeB))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddPontoA)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPontosEquipeB)
                            .addComponent(labelPontosEquipeA))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRemovePontoA)
                            .addComponent(btnRemovePontoB)))
                    .addComponent(btnAddPontoB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    public JTable getTableSets() {
        return tableSets;
    }

    public JLabel getLabelEquipeA() {
        return labelEquipeA;
    }

    public JLabel getLabelEquipeB() {
        return labelEquipeB;
    }

    public JLabel getLabelPontosEquipeA() {
        return labelPontosEquipeA;
    }

    public JLabel getLabelPontosEquipeB() {
        return labelPontosEquipeB;
    }

    public JLabel getLabelSet() {
        return labelSet;
    }

    public void addActionListenerBtnAddPontoA(ActionListener al){
        btnAddPontoA.addActionListener(al);
    }
    
    public void addActionListenerBtnAddPontoB(ActionListener al){
        btnAddPontoB.addActionListener(al);
    }
    
    public void addActionListenerBtnRemovePontoA(ActionListener al){
        btnRemovePontoA.addActionListener(al);
    }
    
    public void addActionListenerBtnRemovePontoB(ActionListener al){
        btnRemovePontoB.addActionListener(al);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPontoA;
    private javax.swing.JButton btnAddPontoB;
    private javax.swing.JButton btnRemovePontoA;
    private javax.swing.JButton btnRemovePontoB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEquipeA;
    private javax.swing.JLabel labelEquipeB;
    private javax.swing.JLabel labelPontosEquipeA;
    private javax.swing.JLabel labelPontosEquipeB;
    private javax.swing.JLabel labelSet;
    private javax.swing.JTable tableSets;
    // End of variables declaration//GEN-END:variables
}
